version: '3'
services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
  # nodetest:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   command: ["npm","run","test"]

